name: automate make README file

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'
        GITHUB_TOKEN: ${{secrets.ACCESS_TOKEN}}
    - name: npm install, build README file
      run: |
        npm install
        npm run make:docs
      env:
        CI: true
    - name: Commit files
      run: |
        echo ${{ github.ref }}
        git add README.md .template/cache.json
        git config --local user.email "githubactionbot+wp@gmail.com"
        git config --local user.name "WP Github Action Bot"
        git commit -m "ci: Automated build" -a | exit 0
    - name: Push changes
      if: github.ref == 'refs/heads/master'
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.ACCESS_TOKEN }}