name: Build Readme Automatic

on: 
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@master
    
    - name: Deploy
      run: |
        node run.js
      env:
        CI: true
